version: 0.2

phases:
  install:
    commands:
      - echo "Installing backend dependencies..."
      - cd application/backend && npm ci && cd ../..

      - echo "Installing frontend dependencies..."
      - cd application/frontend && npm ci && cd ../..

  build:
    commands:
      - echo "Testing backend..."
      - cd application/backend
      - npm start &
      - sleep 5
      - curl --fail http://localhost:3000/health
      - pkill -f "node"
      - cd ../..

      - echo "Testing frontend..."
      - cd application/frontend
      - npm run lint
      - npm run build
      - cd ../..

      - echo "Tests passed."