AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template for AWS CodeBuild project for the course end project

Parameters:
  CodeBuildRoleArn:
    Type: String
  FrontendRepositoryUri:
    Type: String
  BackendRepositoryUri:
    Type: String
  ProjectName:
    Type: String
    Description: Project name used for resource naming
  Environment:
    Type: String
    Description: Environment name used for resource naming

Resources:
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub '${ProjectName}-CodeBuild-Project'
      Description: CodeBuild project for the course end project
      ServiceRole: !Ref CodeBuildRoleArn
      Source:
        Type: CODEPIPELINE
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_LARGE
        Image: aws/codebuild/standard:7.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: AWS_REGION
            Value: !Ref "AWS::Region"
          - Name: FRONTEND_REPOSITORY_URI
            Value: !Ref FrontendRepositoryUri
          - Name: BACKEND_REPOSITORY_URI
            Value: !Ref BackendRepositoryUri
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-CodeBuild-Project'
        - Key: Environment
          Value: !Ref Environment

  TestProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub '${ProjectName}-Test'
      ServiceRole: !Ref CodeBuildRoleArn
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec-test.yml
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_LARGE
        Image: aws/codebuild/standard:7.0
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-CodeBuild-Test'
        - Key: Environment
          Value: !Ref Environment

Outputs:
  CodeBuildProjectName:
    Description: Name of the CodeBuild project
    Value: !Ref CodeBuildProject
  CodeBuildProjectArn:
    Description: ARN of the CodeBuild project
    Value: !GetAtt CodeBuildProject.Arn
  TestProjectName:
    Value: !Ref TestProject