AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to build course end project VPC

Parameters:

  VPCCidr:
    Type: String
    Description: VPC CIDR block

  PublicSubnetACidr:
    Type: String
    Description: Public subnet A CIDR block

  PublicSubnetBCidr:
    Type: String
    Description: Public subnet B CIDR block

  PrivateSubnetACidr:
    Type: String
    Description: Private subnet A CIDR block

  PrivateSubnetBCidr:
    Type: String
    Description: Private subnet B CIDR block

  FrontendPort:
    Type: Number
    Description: Frontend application port

  BackendPort:
    Type: Number
    Description: Backend application port

  ProjectName:
    Type: String
    Description: Project name used for resource naming

  Environment:
    Type: String
    Description: Environment name used for resource naming

Resources:

  # ---------------- VPC ----------------
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-VPC'
        - Key: Environment
          Value: !Ref Environment

  IGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-IGW'
        - Key: Environment
          Value: !Ref Environment

  AttachIGW:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref IGW

  RouteTablePublic:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-Public-RouteTablePublic'
        - Key: Environment
          Value: !Ref Environment

  RoutePublic:
    Type: AWS::EC2::Route
    DependsOn: AttachIGW
    Properties:
      RouteTableId: !Ref RouteTablePublic
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IGW

  NatEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-NAT-EIP'
        - Key: Environment
          Value: !Ref Environment

  NatGateway:
    Type: AWS::EC2::NatGateway
    DependsOn:
      - AttachIGW
      - PublicSubnetA
    Properties:
      AllocationId: !GetAtt NatEIP.AllocationId
      SubnetId: !Ref PublicSubnetA
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-NAT-Gateway'
        - Key: Environment
          Value: !Ref Environment

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-Private-RouteTable'
        - Key: Environment
          Value: !Ref Environment

  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway

  PrivateSubnetARoute:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetA
      RouteTableId: !Ref PrivateRouteTable

  PrivateSubnetBRoute:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetB
      RouteTableId: !Ref PrivateRouteTable

  # ---------------- Subnets ----------------
  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnetACidr
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true

  PublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnetBCidr
      AvailabilityZone: !Select [1, !GetAZs '']
      MapPublicIpOnLaunch: true

  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnetACidr
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: false

  PrivateSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnetBCidr
      AvailabilityZone: !Select [1, !GetAZs '']
      MapPublicIpOnLaunch: false

  PublicSubnetARoute:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetA
      RouteTableId: !Ref RouteTablePublic

  PublicSubnetBRoute:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetB
      RouteTableId: !Ref RouteTablePublic

  # ---------------- Security Groups ----------------
  ALBSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: ALB Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref FrontendPort
          ToPort: !Ref FrontendPort
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-ALB-SG'
        - Key: Environment
          Value: !Ref Environment

  FrontendSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Frontend SG
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref FrontendPort
          ToPort: !Ref FrontendPort
          SourceSecurityGroupId: !Ref ALBSG
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-Frontend-SG'
        - Key: Environment
          Value: !Ref Environment

  BackendSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Backend security group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref BackendPort
          ToPort: !Ref BackendPort
          SourceSecurityGroupId: !Ref FrontendSG
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-Backend-SG'
        - Key: Environment
          Value: !Ref Environment

  # ---------------- ALB ----------------
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub '${ProjectName}-ALB'
      Subnets:
        - !Ref PublicSubnetA
        - !Ref PublicSubnetB
      SecurityGroups:
        - !Ref ALBSG
      Scheme: internet-facing
      Type: application
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-ALB'
        - Key: Environment
          Value: !Ref Environment

  # ---------------- Frontend Target Groups ----------------
  FrontendBlueTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub '${ProjectName}-Frontend-Blue-TG'
      VpcId: !Ref VPC
      Port: !Ref FrontendPort
      Protocol: HTTP
      TargetType: ip

      HealthCheckPath: /
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2

      Matcher:
        HttpCode: 200

      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-Frontend-Blue-TG'
        - Key: Environment
          Value: !Ref Environment

  FrontendGreenTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub '${ProjectName}-Frontend-Green-TG'
      VpcId: !Ref VPC
      Port: !Ref FrontendPort
      Protocol: HTTP
      TargetType: ip

      HealthCheckPath: /
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2

      Matcher:
        HttpCode: 200

      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-Frontend-Green-TG'
        - Key: Environment
          Value: !Ref Environment

  HTTPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      Port: !Ref FrontendPort
      Protocol: HTTP
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            StatusCode: '404'
            ContentType: text/plain
            MessageBody: Not Found

  FrontendListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref HTTPListener
      Priority: 1
      Conditions:
        - Field: path-pattern
          Values:
            - '/*'
      Actions:
        - Type: forward
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn: !Ref FrontendBlueTargetGroup
                Weight: 1
              - TargetGroupArn: !Ref FrontendGreenTargetGroup
                Weight: 0

Outputs:

  VPCId:
    Description: VPC ID
    Value: !Ref VPC

  PublicSubnetAId:
    Description: Public Subnet A ID
    Value: !Ref PublicSubnetA

  PublicSubnetBId:
    Description: Public Subnet B ID
    Value: !Ref PublicSubnetB

  PrivateSubnetAId:
    Description: Private Subnet A ID
    Value: !Ref PrivateSubnetA

  PrivateSubnetBId:
    Description: Private Subnet B ID
    Value: !Ref PrivateSubnetB

  FrontendSecurityGroupId:
    Description: Frontend Security Group ID
    Value: !Ref FrontendSG

  BackendSecurityGroupId:
    Description: Backend Security Group ID
    Value: !Ref BackendSG

  FrontendBlueTargetGroupArn:
    Description: Frontend blue target group ARN
    Value: !Ref FrontendBlueTargetGroup

  FrontendGreenTargetGroupArn:
    Description: Frontend green target group ARN
    Value: !Ref FrontendGreenTargetGroup

  FrontendListenerRuleArn:
    Description: Frontend production listener rule ARN
    Value: !Ref FrontendListenerRule

  HTTPListenerArn:
    Description: ALB HTTP listener ARN
    Value: !Ref HTTPListener

  ALBDNSName:
    Description: ALB DNS Name
    Value: !GetAtt ALB.DNSName